### ISSUE TITLE
How can I visualize the Minecraft?

### ISSUE THREAD

**Issue by RobotiX101** [JiuTian-VL/Optimus-1#3]
Server and diamond scripts started successfully, before set OPENAI_KEY, how can I visualize the progress?

![image](https://github.com/user-attachments/assets/923ce1f0-dd71-4194-a6bb-dcac8a558e6f)

**Comment by RobotiX101** [comment]
After finish the main process, the video is saved. I wonder if I can render at screen while it running.

**Comment by lizaijing** [comment]
We built the architecture with server-side and client-side separation to support plug-and-play for various models. However, we found a bug that visualizing the game process on the server-side sometimes caused the process to run down. We have not yet solved the problem. Once the issue is resolved, we will make the visualization script publicly available.
